version: "3"
services:
  xyz-hub:
    image: xyzmaps/xyz-hub
    container_name: xyz-hub
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  postgres:
    image: xyzmaps/xyz-postgres
    container_name: postgres
    ports:
      - "5432:5432"
    userns_mode: keep-id
    volumes:
      - ./data:/var/lib/postgresql/data:z
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 20s
  docs:
    image: xyzmaps/xyz-docs
    container_name: xyz-docs
    ports:
      - "9000:80"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8888:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:8080/hub/static/openapi/stable.yaml
  redoc-ui:
    image: redocly/redoc
    container_name: redoc-ui
    ports:
      - "8889:80"
    environment:
      - SPEC_URL=http://localhost:8080/hub/static/openapi/stable.yaml
